<?php

/**
 * Implements hook_theme().
 */
function prices_theme() {
    return array(
        'prices' => array(
            'template' => 'templates/price',
            'variables' => array('club' => 0, 'block' => 'block_7'),
        ),
    );
}

/**
 * Implements hook_menu().
 */
function prices_menu() {
    $items['price'] = array(
        'page callback' => 'prices_nagatino_page',
        'access callback' => TRUE,
    );

    $items['price'] = array(
        'page callback' => 'prices_nagatino_page',
        'access callback' => TRUE,
    );

    $items['ajax/prices/%'] = array(
        'page callback' => 'prices_get_club',
        'page arguments' => array(2),
        'access callback' => TRUE,
        'access arguments' => true,
    );

    return $items;
}

function prices_get_club($id){
    $template = theme('prices', array('club' => $id));
    drupal_json_output(array('template' => $template));
}

function prices_nagatino_page(){
    $path = drupal_get_path('module', 'prices');
    drupal_add_js($path . "/js/price.js");
    drupal_add_css($path . "/css/price.css");
    $output = "<div id='wrapper-prices'>";
        $output .= theme('prices', array('club' => $_COOKIE['clubtid']));
    $output .= '</div>';
    return $output;
}

function prices_preprocess_page(&$vars, $hook) {
    if(arg(0)=='price'){
        $vars['title']=t('Цены');

    }
}